from typing import Protocol

from src.blocks import Block


class IWorld(Protocol):
    def set_block(self, x: float, y: float, block: Block) -> bool: ...
    def destroy_block(self, x: int, y: int) -> Block | None: ...
    def is_solid(self, x: float, y: float) -> bool: ...
    def get_block(self, x: float, y: float) -> Block | None: ...
